# Site settings
title: AlbertoÏ€
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Alberto Pilato. I share about my job, technology, bikes, cars and my travels.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: albertopilato
github_username:  albertopi

# Build settings
markdown: kramdown
